const screenTexts = {
  percentSign: '%',
  clearCurrentOperation: 'CE',
  clearAllOperation: 'C',
  deleteNumber: 'DEL',
  reciprocal: '1/x',
  square: 'x^2',
  rootSquare: 'x^0.5',
  addition: '+',
  subtraction: '-',
  multiplication: '*',
  division: '/',
  equal: '=',
  decimalPoint: '.',
  sign: '+/_',
  zero: '0',
  one: '1',
  two: '2',
  three: '3',
  four: '4',
  five: '5',
  six: '6',
  seven: '7',
  eight: '8',
  nine: '9',
};
export default screenTexts;
